"""Private guardians

Revision ID: 13466a1627a5
Revises: 57078a897864
Create Date: 2015-07-12 14:46:20.220745

"""

# revision identifiers, used by Alembic.
revision = '13466a1627a5'
down_revision = '57078a897864'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardian', sa.Column('private', sa.Boolean(), nullable=False, server_default='false'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guardian', 'private')
    ### end Alembic commands ###
