"""Nullable phone number

Revision ID: 1a6db80a68d7
Revises: 94ba95bbecf
Create Date: 2015-07-12 16:36:16.825082

"""

# revision identifiers, used by Alembic.
revision = '1a6db80a68d7'
down_revision = '94ba95bbecf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('korist', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('korist', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    ### end Alembic commands ###
