"""Um

Revision ID: 4a41a29ec5f5
Revises: 1a6db80a68d7
Create Date: 2015-07-12 18:16:27.405867

"""

# revision identifiers, used by Alembic.
revision = '4a41a29ec5f5'
down_revision = '1a6db80a68d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('korist__guardian')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('korist__guardian',
    sa.Column('korist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guardian_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], [u'guardian.id'], name=u'korist__guardian_guardian_id_fkey'),
    sa.ForeignKeyConstraint(['korist_id'], [u'korist.id'], name=u'korist__guardian_korist_id_fkey')
    )
    ### end Alembic commands ###
