"""Nullable again

Revision ID: 57078a897864
Revises: 35c4ab1bfdda
Create Date: 2015-07-12 14:45:12.726474

"""

# revision identifiers, used by Alembic.
revision = '57078a897864'
down_revision = '35c4ab1bfdda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('korist', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('korist', 'mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('korist', 'mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('korist', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###
