"""Renaming columns

Revision ID: a41e6cd1dcb
Revises: 35c4ab1bfdda
Create Date: 2015-07-12 14:00:16.560232

"""

# revision identifiers, used by Alembic.
revision = 'a41e6cd1dcb'
down_revision = '35c4ab1bfdda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('korist', 'email',
        existing_type=sa.VARCHAR(length=255),
        new_column_name='email1')
    op.alter_column('korist', 'phone',
        existing_type=sa.VARCHAR(length=15),
        new_column_name='phone1')
    op.alter_column('korist', 'mobile',
        existing_type=sa.VARCHAR(length=255),
        new_column_name='phone2')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('korist', 'email1',
        existing_type=sa.VARCHAR(length=255),
        new_column_name='email')
    op.alter_column('korist', 'phone1',
        existing_type=sa.VARCHAR(length=15),
        new_column_name='phone')
    op.alter_column('korist', 'phone2',
        existing_type=sa.VARCHAR(length=255),
        new_column_name='mobile')
    ### end Alembic commands ###
